### ISSUE TITLE
Cape render clipping

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/skinpreview3d.js#4]
Changing the call of [toCapeVertices](https://github.com/Hacksore/skinpreview3d.js/blob/master/js/skinpreview3d.js#L389) to add a tiny bit of decimal precision will mitigate this.
```javascript
toCapeVertices(11.01, 1, 11, 17)
```

However, I don't believe it's the right solution to the problem. @yushijinhun do you have any ideas?

## Video of the issue
![tzkcgho](https://user-images.githubusercontent.com/996134/29996861-2c874b02-8fcc-11e7-9781-4c89d9007e6c.gif)

**Comment by yushijinhun** [comment]
I had the same problem before. But now I cannot reproduce it on Firefox 55.0.2(Mobile; Android). So I guess it might be a platform-dependent problem. Based on your experiences, I guess it might be a float-number error.
The cape does not contain any green pixels, but it does have some transparent pixels. I'm confused about where the green comes from. Maybe they're from dirty buffers?
When I last saw the problem, I was using a skin and a cape which neither of them contains black pixels, but the corners were rendered as black.
I will test this on some other platforms and see where the problem actually is.

**Comment by Hacksore** [comment]
For clarification, I created the green pixels for debugging. Sorry for not stating that previously.

Update:
On my desktop Windows PC running Chrome or Firefox, I see this issue. However, on my MacBook running Safari or Chrome, I do not see this.

As you said this is seeming to be platform specific issue. We are on the latest build of Three.js so I'm not sure what the root cause is.

**Comment by yushijinhun** [comment]
I didn't see this problem on my laptop(Firefox 55.0.2; Linux; X11). I checked the calculation results of coordinates but didn't find floating number errors in them. As divisors are powers of 2, I don't think the calculation will bring floating number errors.

**Comment by Hacksore** [comment]
On my Windows PC I used FF v55.0.3 and still had the issue.

**Comment by yushijinhun** [comment]
I'm still not clear about what the problem is. Are you using [`debug_cape.png
`](https://github.com/Hacksore/skinpreview3d.js/blob/c3cfd2fdac3c4c46e0bf408ce83f86f3c21e8cf4/img/debug_cape.png) for testing? The green and blue pixels you have drawn in that image are in the display area. So the expected behaviour is that the corners of the cape are rendered as blue or green, but according to your video, the actual behaviour is that the corners are half red and half blue. But I not certainly sure whether it's what it really looks like, or just noise of GIF picture.
